-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Accounts"
(
    ac_id integer NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Accounts_pkey" PRIMARY KEY (ac_id)
);

CREATE TABLE IF NOT EXISTS public."Favorites"
(
    fa_id integer NOT NULL,
    ac_id integer NOT NULL,
    movie character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Favorites_pkey" PRIMARY KEY (fa_id)
);

CREATE TABLE IF NOT EXISTS public."Groups"
(
    gr_id integer NOT NULL,
    owner integer NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Groups_pkey" PRIMARY KEY (gr_id)
);

CREATE TABLE IF NOT EXISTS public."Members"
(
    me_id integer NOT NULL,
    "group" integer NOT NULL,
    member integer NOT NULL,
    CONSTRAINT "Members_pkey" PRIMARY KEY (me_id)
);

CREATE TABLE IF NOT EXISTS public."Ratings"
(
    ra_id integer NOT NULL,
    movie character varying COLLATE pg_catalog."default" NOT NULL,
    stars smallint NOT NULL DEFAULT 0,
    text character varying COLLATE pg_catalog."default",
    "time" timestamp with time zone NOT NULL,
    ac_id integer NOT NULL,
    CONSTRAINT "Ratings_pkey" PRIMARY KEY (ra_id)
);

ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT ac_id FOREIGN KEY (ac_id)
    REFERENCES public."Accounts" (ac_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Groups"
    ADD CONSTRAINT ac_id FOREIGN KEY (owner)
    REFERENCES public."Accounts" (ac_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Members"
    ADD CONSTRAINT ac_id FOREIGN KEY (member)
    REFERENCES public."Accounts" (ac_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Members"
    ADD CONSTRAINT gr_id FOREIGN KEY ("group")
    REFERENCES public."Groups" (gr_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Ratings"
    ADD CONSTRAINT ac_id FOREIGN KEY (ac_id)
    REFERENCES public."Accounts" (ac_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;